[package]
name = "qrust"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
reqwest = "0.12.11"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.43.0", features = ["full"] } 
url = "2.5.4"

